version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: project_website
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST = localhost
      - MYSQL_USER = root
      - MYSQL_PASSWORD = 
      - MYSQL_DB = login_proj
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "3000:5000"
    container_name: moe-nodejs-app
  mysql:
    image: mysql:latest
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD = root
      - MYSQL_USER = root
      - MYSQL_PASSWORD =  
      - MYSQL_DATABASE = login_proj
    ports:
      - "3001:3306"
    container_name: moe-mysql-app
networks:
  frontend:
  backend: